name: Deploy on github pages using Ubuntu-latest
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: npm run deploy
